export enum TransactionTypes {
    ferry = "ferry",
    bus = "bus",
    flight = "flight",
    flightnonlcc = "flightnonlcc",
    hotel = "hotel",
    insurance = "insurance",
    topup = "topup",
    visa = "visa",
    refund = "refund",
    refund_debit = "refund_debit",
    billspayment = "billspayment",
    package = "package",
    attractions = "attractions",
    credit_transfer = "credit_transfer",
    credit_transfer_debit = "credit_transfer_debit",
}